spring.application.name=numisfera

# Configuraciones de base de datos (H2 Memoria por defecto para Desarrollo Local)
spring.datasource.url=jdbc:h2:mem:numisferadb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Storage Settings
app.images.max-uploads=3
app.storage.provider=local
app.storage.local.upload-dir=uploads

# Spring limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
